### PR TITLE
Make clickLink look for links with aria-label and alt text

### LINKED ISSUE #158: ProgramTest.clickLink does not work if you have no text
I have a situation in which I have an image (actually an svg which is the entire link, with no text nodes, corresponding to something like:

```elm
Html.a
    [ Attributes.href ... ]
    [ Svg.svg [] [ Svg. ...] ]
```

If I attempt to use `ProgramTest.clickLink "" url` it doesn't work because the selector attempts to find a text node containing the empty string and fails because it doesn't find any text node at all. 

I can solve this by adding an empty text node, as in:

```elm
Html.a
    [ Attributes.href ... ]
    [ Svg.svg [] [ Svg. ...]
    -- Added to satisfy ProgramText.clickLink
    , Html.text ""
    ]
```

This seems a **little** unsatisfactory. I guess a way to solve this would be to make the text argument to `ProgramTest.clickLink` a `Maybe String`. I guess the same applies to `ProgramTest.clickButton`. It would make the resulting [code for the selector](https://github.com/avh4/elm-program-test/blob/3.6.2/src/ProgramTest.elm#L1005) a little awkward, you would have to change this

```elm
findLinkTag =
            [ Selector.tag "a"
            , Selector.attribute (Html.Attributes.href href)
            , Selector.containing [ Selector.text linkText ]
            ]
```

into something like:

```elm
commonTagSelectors =
            [ Selector.tag "a"
            , Selector.attribute (Html.Attributes.href href)
             ]

findLinkTag =
      case mLinkText of
           Nothing ->
               commonTagSelectors
           Just linkText ->
                List.append
                      commonTagSelectors
                      [ Selector.containing [ Selector.text linkText ] ]
```

Or, since there doesn't seem to be a `Selector.matchAnything`
```elm
findLinkTag =
            [ Selector.tag "a"
            , Selector.attribute (Html.Attributes.href href)
            , case mLinkText of
                  Nothing ->
                      Selector.all []
                  Just linkText -> 
                       Selector.containing [ Selector.text linkText ]
            ]
```

As I say, there **is** a workaround, it just feels a little unsatisfactory.

### PR DESCRIPTION
**Pull request by nunntom**
Hi @avh4. While I was on a roll I decided to have a look at #158, because I'm also running into this issue where I am using icons in links with an aria-label.

See what you think.

Closes #158 

- [x] ran tests locally with `npm test`
- [ ] updated CHANGELOG.md if appropriate

### CODE REVIEW

File: src/ProgramTest.elm [hunk 1]
```diff
@@ -1048,17 +1075,12 @@ clickLink linkText href programTest =
...
-                    let
-                        link =
-                            Program.renderView program state.currentModel
-                                |> Query.find findLinkTag
-                    in
-                    if respondsTo normalClick link then
-                        -- there is a click handler
-                        -- first make sure the handler properly respects "Open in new tab", etc
-                        if respondsTo ctrlClick link || respondsTo metaClick link then
+            if respondsTo normalClick then
```
Comment (avh4) [inline src/ProgramTest.elm:1078]: I'm having a little bit of trouble convincing myself this refactoring is correct now that `repondsTo` doesn't take the found link element as an input.  I guess it's that `repondsTo` is re-running the original query, just modified to do the simulate as the last step of each branch?

Apart from being a bit confusing to read, it makes me a little nervous about the performance if we're re-doing that work, since ComplexQuery can be quite slow (especially when a query fails).

Here's one possible thought: maybe we could extract a new function from `simulateComplexQuery`/`assertComplexQuery`:

```elm
runComplexQuery :
    String
    -> (ComplexQuery (Query.Single msg) -> ComplexQuery a)
    -> (Program model msg effect (SimulatedSub msg) -> TestState model msg effect -> a ->  Result Failure (TestState model msg effect))
    -> ProgramTest model msg effect
    -> ProgramTest model msg effect

simulateComplexQuery functionName complexQuery =
    runComplexQuery functionName complexQuery <| \program state msg -> TestState.update msg program state

assertComplexQuery functionName complexQuery =
    runComplexQuery functionName complexQuery <| _ state _ -> state
```

And then here we could use `runComplexQuery` with the `findLinkQuery` to get the single, and a function that will take the single and use it to "try clicking", and then we wouldn't have to re-find the single in each call of `respondsTo`?

File: src/ProgramTest.elm [hunk 2]
```diff
@@ -1009,12 +1009,39 @@ clickLink linkText href programTest =
...
             "clickLink " ++ String.Extra.escape linkText
 
-        findLinkTag =
-            [ Selector.tag "a"
-            , Selector.attribute (Html.Attributes.href href)
-            , Selector.containing [ Selector.text linkText ]
+        findLinkQuery =
+            [ ( "<a> with text"
+              , ComplexQuery.find (Just "find link")
+                    [ "link" ]
```
Comment (avh4) [inline src/ProgramTest.elm:1015]: If I remember correctly, this argument is a list of html tags that will be kept expanded when the ComplexQuery error renderer tries to condense down the HTML out.  So this should be `[ "a" ]`, not "link".

File: tests/ProgramTestTests/UserInput/ClickLinkTest.elm [hunk 3]
```diff
@@ -48,6 +54,16 @@ all =
...
+        , test "can verify a link with aria-label" <|
+            \() ->
+                linkProgram
+                    |> ProgramTest.clickLink "Aria" "https://example.com/link"
+                    |> ProgramTest.expectPageChange "https://example.com/link"
+        , test "can verify a link with img and alt text" <|
+            \() ->
+                linkProgram
+                    |> ProgramTest.clickLink "Alt Text" "https://example.com/link"
+                    |> ProgramTest.expectPageChange "https://example.com/link"
```
Comment (avh4) [inline tests/ProgramTestTests/UserInput/ClickLinkTest.elm:66]: 💯

File: src/ProgramTest.elm (hunk 1 above)
Comment (nunntom) [reply src/ProgramTest.elm]: Good point! Not sure what I was thinking implementing it that way. I think it was running the query five times! I actually later came up with something along the lines of your suggestion independently. I've now implemented `runComplexQuery` (with a slight change of argument order) and pushed.

`assertComplexQuery` is not being used now. Not sure if it's worth keeping it around.

File: src/ProgramTest.elm (hunk 2 above)
Comment (nunntom) [reply src/ProgramTest.elm]: Got it. I was wondering what this did.

**Comment by avh4** [comment]
(I'll get to this tomorrow if I don't have time for it today.)

File: src/ProgramTest.elm (hunk 1 above)
Comment (avh4) [reply src/ProgramTest.elm]: Yeah, there have been many times on this project where I've implemented something, and then when I show it to someone they ask why I did it so complicated 😄 

It's fine to leave `assertComplexQuery` for now, especially since I haven't finished reviewing if there are more functions that should be ported over to using ComplexQuery internally.

**Comment by avh4** [comment]
Looks great, thank you!!
